# Generated by Django 2.2.5 on 2021-07-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20210601_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='how many people will be staying?', null=True),
        ),
    ]
